#ifndef  __TREEMENU_SERVICEDEF_H__
#define  __TREEMENU_SERVICEDEF_H__

//=== ServiceDef.h ===
//SERVICE NUMBER DEFINE
#define D_TREEMENU_DO_MODAL            	           1
#define D_TREEMENU_MODELESS            	           2

// DLG NUMBER DEFINE
#define D_TREEMENU_DO_AFX_TESTMSG                  1
#define D_TREEMENU_DO_WINDP_CH2012_CONSIDER_CRSTOR 2
#define D_TREEMENU_DO_WINDP_KBC2009_AUTOFORCECOEF  3
#define D_TREEMENU_DO_WINDP_WINDPROFILE            4
#define D_TREEMENU_DO_WINDP_CH2001_MAGFACTOR       5
#define D_TREEMENU_DO_WINDP_NODAL_STRUCTURE        6
#define D_TREEMENU_DO_WINDP_KBC2016_WINDDIR		   7
#define D_TREEMENU_DO_WINDP_KBC2016_STRUCT		   8
#define D_TREEMENU_DO_WINDP_WINDPROFILEKBC2016     9
#define D_TREEMENU_DO_WINDP_CH2019_CONSIDER_CRSTOR 10
#define D_TREEMENU_DO_EARTHP_STATIC_PROFILE        11
#define D_TREEMENU_DO_EARTHP_SEISMIC_PROFILE       12
#define D_TREEMENU_DO_WINDP_ASCE7_16_STRUCT		   13

#endif
