#ifndef __DB_ST_DT_ANALYSIS_H__
#define __DB_ST_DT_ANALYSIS_H__

#define MIDAS_SDK

enum AnalysisTypeId
{
	D_ANALYSIS_TYPE_MAIN=0,
	D_ANALYSIS_TYPE_MAIN_IML,
	D_ANALYSIS_TYPE_MAIN_SNA,
	D_ANALYSIS_TYPE_PUSHOVER,
	D_ANALYSIS_TYPE_GRIDMODEL,
	D_ANALYSIS_TYPE_GRIDMODEL_MASSCONVERTER,
	D_ANALYSIS_TYPE_STAGECREEP_INFLGRID,
	D_ANALYSIS_TYPE_STAGECREEP_GRIDMODEL,
	D_ANALYSIS_TYPE_STAGECREEP_MAIN,
	D_ANALYSIS_TYPE_IMPORTRESULT,
	D_ANALYSIS_TYPE_DESIGN,
	D_ANALYSIS_TYPE_PCDESIGN,
	D_ANALYSIS_TYPE_BRIDGELOADRATING,
	D_ANALYSIS_TYPE_STL_BRIDGELOADRATING,
	D_ANALYSIS_TYPE_RC_BRIDGELOADRATING,
	D_ANALYSIS_TYPE_PLATEGIRDER,
	D_ANALYSIS_TYPE_STL_ORTH_DECK,
	D_ANALYSIS_TYPE_STL_COMP_GIRDER,
	D_ANALYSIS_TYPE_SUSPENSION_WIZARD,
	D_ANALYSIS_TYPE_SUSPENSION_USER,
	D_ANALYSIS_TYPE_NEXT,
	D_ANALYSIS_TYPE_TEST_PSC,
	D_ANALYSIS_TYPE_UNKNOWNFACTOR,

// [30/10/2006 : maxiao] For CIVIL(CH) 2006                                        
	D_ANALYSIS_TYPE_CHRCBeamDESIGN,
	D_ANALYSIS_TYPE_CHRCColumnDESIGN,
	D_ANALYSIS_TYPE_CHRCSEISMICDESIGN,

	D_ANALYSIS_TYPE_CRACK,

	D_ANALYSIS_TYPE_JUD,
	D_ANALYSIS_TYPE_PLATE_BC_DESIGN,

	D_ANALYSIS_TYPE_SECOND_PHASE_PENDING
};

#endif  // __DB_ST_DT_ANALYSIS_H__
