// DgnMsgAcs.h: interface for the CDgnMsgAcs class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_DGNMSGACS_H__C0F7A37D_A7EC_46EA_8C6D_48B8760F6665__INCLUDED_)
#define AFX_DGNMSGACS_H__C0F7A37D_A7EC_46EA_8C6D_48B8760F6665__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
//---------Add by Yellowbug 2002.07.06
#include "..\MIT_Lib\rptostream.h"
#include "DgnMsgDgn.h"
#include "HeaderPre.h"

class __MY_EXT_CLASS__ CDgnMsgAcs : public CDgnMsgDgn  
{

public:
	CDgnMsgAcs();
	virtual ~CDgnMsgAcs();
public:

//------------ADD by Yellowbug 2002.08.09
	LPCTSTR Msg_acs_STEEL_DESIGN();    
	LPCTSTR Msg_acs_1_DESIGN_INFO();
	LPCTSTR Msg_acs_CODE();
	LPCTSTR Msg_acs_UNIT_SYSTEM();
	LPCTSTR Msg_acs_ELEMENT_NO();
	LPCTSTR Msg_acs_MATERIAL();
	LPCTSTR Msg_acs_NO();
	LPCTSTR Msg_acs_SECTION_NAME();
	LPCTSTR Msg_acs_POSITION();
	LPCTSTR Msg_acs_TAPERTED_SECTION();
	LPCTSTR Msg_acs_POSITION_J();
	LPCTSTR Msg_acs_BUILT_UP_SECTION();
	LPCTSTR Msg_acs_ROLLED();
	LPCTSTR Msg_acs_MEMBER_LENGTH();
	LPCTSTR Msg_acs_DEPTH();
	LPCTSTR Msg_acs_WEB_THICK();
	LPCTSTR Msg_acs_TOP_FWIDTH();
	LPCTSTR Msg_acs_BOT_LFWIDTH();
	LPCTSTR Msg_acs_BOT_RFWIDTH();
	LPCTSTR Msg_acs_TOP_FTHICK();
	LPCTSTR Msg_acs_BOT_FWIDTH();
	LPCTSTR Msg_acs_BOT_FTHICK();
	LPCTSTR Msg_acs_FLG_WIDTH();
	LPCTSTR Msg_acs_WEB_CENTER();
	LPCTSTR Msg_acs_OUT_DIA();
	LPCTSTR Msg_acs_WALL_THICK();
	LPCTSTR Msg_acs_WIDTH();
	LPCTSTR Msg_acs_FLG_THICK();
	LPCTSTR Msg_acs_BTB_SPACE();
	LPCTSTR Msg_acs_THICKNESS();
	LPCTSTR Msg_acs_ROUNDING();
	LPCTSTR Msg_acs_LIP_DEPTH();
	LPCTSTR Msg_acs_AREA();
	LPCTSTR Msg_acs_2_MEM_FORCE();
	LPCTSTR Msg_acs_LOAD_COMB();
	LPCTSTR Msg_acs_AXIAL_FORCE();
	LPCTSTR Msg_acs_SHEAR_FORCE();
	LPCTSTR Msg_acs_BEND_MOMENT();
	LPCTSTR Msg_acs_MOM_END();
	LPCTSTR Msg_acs_2_MEM_CHK_FORCE();
	LPCTSTR Msg_acs_2_MEM_CHK_ITEM_AXIS();
	LPCTSTR Msg_acs_2_MEM_CHK_ITEM_STABLE();
	LPCTSTR Msg_acs_2_MEM_CHK_ITEM_STABLE_Y();
	LPCTSTR Msg_acs_2_MEM_CHK_ITEM_STABLE_Z();
	LPCTSTR Msg_acs_2_MEM_CHK_ITEM_SHEAR();
	LPCTSTR Msg_acs_3_DGN_PARAM_ELEM_TYPE();
	LPCTSTR Msg_acs_3_DGN_PARAM();
	LPCTSTR Msg_acs_EFFECT_LENGTH();
	LPCTSTR Msg_acs_EFFECT_LENGTH_LTB();// MQC:8592 Seungjun-20140905 : Effective length for lateral-torsional-buckling
	LPCTSTR Msg_acs_MOM_CRT_FACTOR();
	LPCTSTR Msg_acs_UNBRC_LENGTH();
	LPCTSTR Msg_acs_EFFECT_LENG_FACTOR();
	LPCTSTR Msg_acs_EQUIP_MOM_FACTOR();
		LPCTSTR Msg_acs_NET_AREA_RATIO();
	LPCTSTR Msg_acs_BEND_COEFF();
	LPCTSTR Msg_acs_MOM_FACTOR();
	LPCTSTR Msg_acs_WTR_NG();
	LPCTSTR Msg_acs_4_STRESS_CHK_RESULT();
	LPCTSTR Msg_acs_AXIAL_STRESS();
	LPCTSTR Msg_acs_PRINTFONT();
	LPCTSTR Msg_acs_SLEND_RATIO();
	LPCTSTR Msg_acs_SLEND_RATIO_KL();
	LPCTSTR Msg_acs_SLEND_RATIO_L();
	LPCTSTR Msg_acs_BENDING_STRESS();
	LPCTSTR Msg_acs_AXIAL_AND_BENDING_STRESS();
	LPCTSTR Msg_acs_MAX_TENSION();
	LPCTSTR Msg_acs_MAJOR_AXIS();
	LPCTSTR Msg_acs_MAX_COMP_TENS();
	LPCTSTR Msg_acs_MAX_COMP();
	LPCTSTR Msg_acs_MINOR_AXIS();
	LPCTSTR Msg_acs_4_STRENGTH_CHK_RESULT();
	LPCTSTR Msg_acs_4_RESIST_CHK_RESULT();
	LPCTSTR Msg_acs_Flexural_STRESS();
	LPCTSTR Msg_acs_Shear_STRESS();
	LPCTSTR Msg_acs_4_RESIST_CHK_RESULT_AXIAL();
	LPCTSTR Msg_acs_4_RESIST_CHK_RESULT_STABLE();
	LPCTSTR Msg_acs_4_RESIST_CHK_RESULT_SHEAR();
	LPCTSTR Msg_acs_AXIAL_STRENGTH();
	LPCTSTR Msg_acs_BEND_STRENGTH();
	LPCTSTR Msg_acs_AXIAL_RESISTANCE();
	LPCTSTR Msg_acs_BEND_RESISTANCE();
	LPCTSTR Msg_acs_COMB_STRESS();
	LPCTSTR Msg_acs_TENS_BEND();
	LPCTSTR Msg_acs_COMP_BEND();
	LPCTSTR Msg_acs_BENDING();
	LPCTSTR Msg_acs_COMB_STRENGTH();
	LPCTSTR Msg_acs_COMB_CAPACITY();
	LPCTSTR Msg_acs_COMB_RESIST();
	LPCTSTR Msg_acs_SHEAR_STRENGTH();
	LPCTSTR Msg_acs_SHEAR_RESIST();
	LPCTSTR Msg_acs_SHEAR_STRESS();
	LPCTSTR Msg_acs_SHEAR_DISENERGY_BEAM();
	LPCTSTR Msg_acs_4_CHK_RESULT();
	LPCTSTR Msg_acs_CHK_SLD_XZV();
	LPCTSTR Msg_acs_CHK_SLD_YZ();
	LPCTSTR Msg_acs_CHK_SLD_V();
	LPCTSTR Msg_acs_SLD_RATIO_LK();
	LPCTSTR Msg_acs_CHK_AXIAL_STRESS();
	LPCTSTR Msg_acs_5_CALC_BOLT_RESULT();
	LPCTSTR Msg_acs_BOLT_NAME_ARR_NUM();
	LPCTSTR Msg_acs_MATERIAL_2();
	LPCTSTR Msg_acs_BOLT_TENS_STRENGTH();
	LPCTSTR Msg_acs_NOT_CALC_BUT_JOINT();
	LPCTSTR Msg_acs_BOLT_SHEAR_STRENGTH();
	LPCTSTR Msg_acs_BOLT_BEAR_STRENGTH();
	LPCTSTR Msg_acs_MEMB_TENS_STRENGTH();
	LPCTSTR Msg_acs_BOLT_CHK_STRENGTH();
	LPCTSTR Msg_acs_ELEM_PROP();
	LPCTSTR Msg_acs_CHK_COM_SHR();
	LPCTSTR Msg_acs_CHK_COM_STR();  // Seungjun-20081209 EC2:05 2nd development.
	LPCTSTR Msg_acs_ELEM_PROP_1();
	LPCTSTR Msg_acs_CHK_COM_SHR_1();
	LPCTSTR Msg_acs_5_STRUCTRE_CHK_RESULT();
	LPCTSTR Msg_acs_5_STRUCTRE_CHK_RESULT_SLENDER();
	LPCTSTR Msg_acs_5_STRUCTRE_CHK_RESULT_WTRATIO();
	LPCTSTR Msg_acs_5_STRUCTRE_CHK_RESULT_DEFLECTION();

	// Coded by Seungjun MNet:No.2393 ('20060907)
	LPCTSTR Msg_acs_5_DEFLECTION_CHK_RESULT();
	LPCTSTR Msg_acs_2_DEFLECTION_CHK_RESULT();
	LPCTSTR Msg_acs_DEFLECTION();
	LPCTSTR Msg_acs_DEFLECTIONforColumn_h();
	LPCTSTR Msg_acs_DEFLECTIONforColumn_h0();
	LPCTSTR Msg_acs_LCB_POS_DIRX();
	LPCTSTR Msg_acs_LCB_POS_DIRY();
	LPCTSTR Msg_acs_LCB_POS_DIRZ();
	// Coded by SeungJun '20080715
	LPCTSTR Msg_acs_TENS_BEND_SHEAR();
	LPCTSTR Msg_acs_COMP_BEND_SHEAR();
	LPCTSTR Msg_acs_AXIAL_BEND();
    LPCTSTR Msg_acs_AXIAL_BEND_SHEAR();
    LPCTSTR Msg_acs_AXIAL_BEND_IRS();
	
	// Add by GAY. MNET:3602. ('08.08.04).
	LPCTSTR Msg_acs_COMP_BEND_SHEAR_TORSION();
	LPCTSTR Msg_acs_TENS_BEND_SHEAR_TORSION();
	LPCTSTR Msg_acs_TORSION_STRENGTH();

	LPCTSTR Msg_acs_COMBINED_RATIO();
	LPCTSTR Msg_acs_BUCKLING_RESIS_COMP();
	LPCTSTR Msg_acs_BUCKLING_RESIS_BENDING();
	LPCTSTR Msg_acs_BUCKLING_RESIS_COMP_BENDING();
	LPCTSTR Msg_acs_SERVICEABLILITY_LIMIT_STATE();
	LPCTSTR Msg_acs_COMBINED_RATIO_BENDING_AXIAL();
	LPCTSTR Msg_acs_COMBINED_RATIO_BENDING_TENS();
	LPCTSTR Msg_acs_COMBINED_RATIO_BENDING_COMP();
	LPCTSTR Msg_acs_FLEXURAL_BUCKLING_WITHOUT_FLEXURAL_BUCKILING();
	LPCTSTR Msg_acs_FLEXURAL_BUCKLING_WITH_FLEXURAL_BUCKILING();
	// Z_Shape Section
	LPCTSTR Msg_acs_LIP_SLOPE();
	LPCTSTR Msg_acs_STRENGTH_CHECK();
	LPCTSTR Msg_acs_CHECK_STABILITY_A_PLANE_BENDING_SHAPE();
	LPCTSTR Msg_acs_STABILITY_CHECK_IN_MOMENT_PLANE_MY();
	LPCTSTR Msg_acs_STABILITY_CHECK_IN_MOMENT_PLANE_MZ();
	LPCTSTR Msg_acs_BENDING_STABILITY_CHECK_IN_2_PLANES();
	LPCTSTR Msg_acs_STABILITY_CHECK_FROM_PLANE_OF_MOMENT();
	LPCTSTR Msg_acs_CHECK_LOCAL_STABILITY_WEB();
	LPCTSTR Msg_acs_CHECK_LOCAL_STABILITY_FLANGE();
	LPCTSTR Msg_acs_CHECK_SLENDERNESS_OF_ELEMENT();
	
	LPCTSTR Msg_acs_Section_Total_CHK_Title();
	LPCTSTR Msg_acs_Section_CHK_KSCE_ASD10_OK();
	LPCTSTR Msg_acs_Section_CHK_KSCE_ASD10_NG();

	LPCTSTR Msg_acs_REQUIRED_CLASS();
	LPCTSTR Msg_acs_REQUIRED_CLASS__s();
};
#include "HeaderPost.h"


#endif // !defined(AFX_DGNMSGACS_H__C0F7A37D_A7EC_46EA_8C6D_48B8760F6665__INCLUDED_)
