/**
 * Type definitions for Accuracy Policy
 * Evidence-based schema generation and validation
 */

export interface Evidence {
    source: 'doc' | 'image' | 'api_spec' | 'code' | 'inferred';
    ref?: string;        // "Section 4.2", "Page 3", "Figure 12"
    quote?: string;      // Exact text from source
    confidence: 'high' | 'medium' | 'low';
}

export interface AutoQuestionPattern {
    id: string;
    trigger: {
        type: 'enum_count' | 'keyword_detection' | 'pattern_match' | 'field_analysis' | 'complexity_check';
        condition?: string;
        keywords?: string[];
        location?: string[];
        pattern?: string;
        threshold?: number;
        fieldTypes?: string[];
        context?: string;
    };
    action: {
        type: 'require_question' | 'suggest_question' | 'flag_for_review';
        priority: 'high' | 'medium' | 'low';
        questionTemplate: string;
        contextTemplate?: string;
    };
    example?: {
        field: string;
        trigger?: string;
        enumSeen?: string[];
        question: string;
    };
}

export interface QualityGate {
    enabled: boolean;
    checks?: string[];
    minimumCoverage?: number;
    criticalFields?: string[];
    minimumQuestions?: number;
    maximumQuestions?: number;
    requireContext?: boolean;
}

export interface AccuracyPolicy {
    version: string;
    extends?: string;
    requireEvidenceFor: string[];
    evidenceFormat: {
        source: {
            type: string;
            values: string[];
        };
        ref: {
            type: string;
            examples: string[];
            optional: boolean;
        };
        quote: {
            type: string;
            description: string;
            optional: boolean;
        };
        confidence: {
            type: string;
            values: string[];
        };
    };
    autoQuestionPatterns: AutoQuestionPattern[];
    validationStrictness: {
        missingEvidenceForEnum: {
            action: 'reject' | 'warn' | 'allow';
            message: string;
        };
        missingEvidenceForDefault: {
            action: 'reject' | 'warn' | 'allow';
            message: string;
        };
        lowConfidenceEvidence: {
            action: 'generate_question' | 'warn' | 'allow';
            threshold: string;
            message: string;
        };
    };
    deterministicRules: {
        enforceFieldOrder: boolean;
        fieldOrderPriority: string[];
        sortEnumValues: boolean;
        enforceKeyNamingConvention: boolean;
        namingConvention: {
            prefix: string;
            casing: string;
        };
    };
    qualityGates: {
        schemaStructure: QualityGate;
        evidenceCompleteness: QualityGate;
        questionQuality: QualityGate;
    };
    hallucinationPrevention: {
        detectUndocumentedFields: {
            enabled: boolean;
            action: string;
        };
        detectUnusualEnumValues: {
            enabled: boolean;
            knownPatterns: string[];
            action: string;
        };
        prohibitInferredDefaults: {
            enabled: boolean;
            allowedSources: string[];
            prohibitedSources: string[];
        };
    };
}

export interface ValidationResult {
    passed: boolean;
    errors: ValidationError[];
    warnings: ValidationWarning[];
    autoQuestions: AutoGeneratedQuestion[];
    evidenceCoverage: number;
}

export interface ValidationError {
    field: string;
    type: 'missing_evidence' | 'invalid_evidence' | 'quality_gate_failed';
    message: string;
    severity: 'error' | 'warning';
}

export interface ValidationWarning {
    field: string;
    message: string;
    suggestion?: string;
}

export interface AutoGeneratedQuestion {
    field: string;
    question: string;
    context: string;
    reason: string;  // Pattern ID that triggered the question
    priority: 'high' | 'medium' | 'low';
}
